# Generated by Django 5.0.4 on 2024-05-16 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_userprofile_file_adminpermission_post_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercontent',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created_at',
            new_name='created_on',
        ),
        migrations.DeleteModel(
            name='AdminPermission',
        ),
        migrations.DeleteModel(
            name='UserContent',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
