# Generated by Django 5.0.4 on 2024-05-16 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_usercontent_user_remove_userprofile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.TextField(default='default', max_length=30),
        ),
    ]
